/** @format */

export const {
  VITE_PROJECT_ID,
  VITE_AUTH_API_ENDPOINT,
  VITE_API_ENDPOINT,
  VITE_SOCKET_API_ENDPOINT,
  VITE_APP_WF_URL,
  VITE_APP_SC_URL,
  VITE_GOOGLE_CLIENT_ID,
  VITE_ROOT_DOMAIN,
  VITE_SEED_AUTH_URL,
  VITE_SEED_CLIENT_ID,
  VITE_SEED_REALM,
  VITE_SAMPLE_SOLUTION_ENDPOINT,
} = import.meta.env;

export const ROUTE_PATH = {
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  LOGOUT: "/logout",
};
