name: Build - Test - Push

on:
  push:
    branches-ignore:
      - experiment

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=4096
      AWS_DEFAULT_REGION: ap-southeast-1    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

  push:
    if: github.ref == 'refs/heads/main'
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to ECR
        run: |
          export AWS_ACCOUNT_ID=`aws sts get-caller-identity --query Account --output text`
          echo "region $AWS_DEFAULT_REGION"
          echo "aws_account_id $AWS_ACCOUNT_ID"
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t wf-platform-fe:${{ github.run_number }} -f Dockerfile .

      - name: Tag Docker image to a common repository used for both Prod and Test env
        run: |
          docker tag wf-platform-fe:${{ github.run_number }} 757923541688.dkr.ecr.ap-southeast-1.amazonaws.com/wf-platform-fe:${{ github.run_number }}

      - name: Push to ECR
        run: |
          docker push 757923541688.dkr.ecr.ap-southeast-1.amazonaws.com/wf-platform-fe:${{ github.run_number }}
          
      - run: |
          echo "🍏 This job's status is ${{ job.status }}."
          echo "Run number - ${{ github.run_number }} "
          docker image ls